name: VS Code Extension

on: [push, pull_request]

jobs:
  vscode-extension:
    name: VS Code Extension
    runs-on: ubuntu-latest

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4

      - name: 🏗 Set up NodeJS
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "14"

      - name: 🏗 Install NodeJS packages
        run: npm install

      - name: 🚀 Run Linter
        run: npm run lint

      - name: 🚀 Run Compile
        working-directory: src/language-service
        run: npm run compile

      - name: 🚀 VSCode Marketplace Publish
        if: success() && github.ref == 'refs/heads/master'
        run: |
          npm install -g vsce
          vsce publish -p $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
